FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npx prisma generate
RUN npx tsc --noEmit || true

CMD ["npx", "ts-node", "--project", "tsconfig.json", "-r", "tsconfig-paths/register", "jobs/start-workers.ts"]
